name: Auto Commit

# Event yang akan memicu workflow berdasarkan jadwal (cron job)
on:
  schedule:
    - cron: "0 0 * * *"  # Cron job yang dijalankan setiap hari pada pukul 00:00 UTC

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout repository ke dalam workflow
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup Git untuk melakukan commit
      - name: Setup Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      # Tambahkan langkah untuk melakukan perubahan otomatis
      - name: Make Changes
        run: |
          echo "Auto update on $(date)" >> changes.txt
          # Tambahkan script lain sesuai kebutuhan

      # Tambahkan dan commit perubahan
      - name: Commit Changes
        run: |
          git add .
          git commit -m "Auto commit from GitHub Actions" || echo "No changes to commit"

      # Dorong perubahan kembali ke branch asal
      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub otomatis menyediakan token ini
        run: |
          git push
